build_config: &build_config
  BUILD_IMAGE_NAME: circleci/openjdk
  BUILD_IMAGE_TAG: 8-jdk-buster
  CACHE_VERSION: v1
  _JAVA_OPTIONS: "-Xmx3g"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

version: 2
jobs:
  build:
    environment:
      <<: *build_config
    docker:
      - image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}
    steps:
      - checkout
      - restore_cache:
          key: ${CACHE_VERSION}-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: ${CACHE_VERSION}-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Install dependencies
          command: ./gradlew build --exclude-task test
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: ${CACHE_VERSION}-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: ${CACHE_VERSION}-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - build

  test:
    environment:
      <<: *build_config
    docker:
      - image: ${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            ./gradlew test
      - run:
          name: Generate code coverage report
          command:
            ./gradlew jacocoTestReport
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - store_artifacts:
          path: build/reports/jacoco/test/html
          when: always
      - run:
          name: Create XNAT plugin jar
          command: |
            ./gradlew xnatPluginJar --exclude-task test
      - store_artifacts:
          path: build/libs
      - run:
          name: Publish XNAT plugin jar
          command: |
            ./gradlew publish -PmavenSettings=./.circleci/settings.xml

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
